vim.keymap.set('n', '<leader>t', vim.cmd.BufferLineCycleNext)
vim.keymap.set('n', '<leader>T', vim.cmd.BufferLineCyclePrev)
vim.keymap.set('n', '<leader>bq<Right>', vim.cmd.BufferLineCloseRight)
vim.keymap.set('n', '<leader>bq<Left>', vim.cmd.BufferLineCloseLeft)
vim.keymap.set('n', '<leader>bq<Down>', vim.cmd.BufferLineCloseOthers)
vim.keymap.set('n', '<leader>bq', vim.cmd.BufferLinePickClose)
vim.keymap.set('n', '<leader>bp', vim.cmd.BufferLineTogglePin)
vim.keymap.set('n', '<leader>bf', vim.cmd.BufferLinePick)
vim.keymap.set('n', '<leader>1', ':BufferLineGoTo 1<CR>')
vim.keymap.set('n', '<leader>2', ':BufferLineGoTo 2<CR>')
vim.keymap.set('n', '<leader>3', ':BufferLineGoTo 3<CR>')
vim.keymap.set('n', '<leader>4', ':BufferLineGoTo 4<CR>')
vim.keymap.set('n', '<leader>5', ':BufferLineGoTo 5<CR>')
vim.keymap.set('n', '<leader>6', ':BufferLineGoTo 6<CR>')
vim.keymap.set('n', '<leader>7', ':BufferLineGoTo 7<CR>')
vim.keymap.set('n', '<leader>8', ':BufferLineGoTo 8<CR>')
vim.keymap.set('n', '<leader>9', ':BufferLineGoTo 9<CR>')
vim.keymap.set('n', '<leader>0', ':BufferLineGoTo 0<CR>')
vim.keymap.set('n', '<leader>q', function ()
  require('bufdelete').bufdelete(0, true)
end)
