vim.keymap.set("n", "<leader>t", vim.cmd.BufferLineCycleNext, { desc = "Next buffer" })
vim.keymap.set("n", "<leader>T", vim.cmd.BufferLineCyclePrev, { desc = "Previous buffer" })
vim.keymap.set("n", "<leader>bq<Right>", vim.cmd.BufferLineCloseRight, { desc = "Close buffers right" })
vim.keymap.set("n", "<leader>bq<Left>", vim.cmd.BufferLineCloseLeft, { desc = "Close buffers left" })
vim.keymap.set("n", "<leader>bq<Down>", vim.cmd.BufferLineCloseOthers, { desc = "Close other buffers" })
vim.keymap.set("n", "<leader>bq", vim.cmd.BufferLinePickClose, { desc = "Pick close buffer" })
vim.keymap.set("n", "<leader>bp", vim.cmd.BufferLineTogglePin, { desc = "Pin buffer" })
vim.keymap.set("n", "<leader>bf", vim.cmd.BufferLinePick, { desc = "Pick buffer" })
vim.keymap.set("n", "<leader>1", ":BufferLineGoTo 1<CR>", { desc = "Go to buffer 1" })
vim.keymap.set("n", "<leader>2", ":BufferLineGoTo 2<CR>", { desc = "Go to buffer 2" })
vim.keymap.set("n", "<leader>3", ":BufferLineGoTo 3<CR>", { desc = "Go to buffer 3" })
vim.keymap.set("n", "<leader>4", ":BufferLineGoTo 4<CR>", { desc = "Go to buffer 4" })
vim.keymap.set("n", "<leader>5", ":BufferLineGoTo 5<CR>", { desc = "Go to buffer 5" })
vim.keymap.set("n", "<leader>6", ":BufferLineGoTo 6<CR>", { desc = "Go to buffer 6" })
vim.keymap.set("n", "<leader>7", ":BufferLineGoTo 7<CR>", { desc = "Go to buffer 7" })
vim.keymap.set("n", "<leader>8", ":BufferLineGoTo 8<CR>", { desc = "Go to buffer 8" })
vim.keymap.set("n", "<leader>9", ":BufferLineGoTo 9<CR>", { desc = "Go to buffer 9" })
vim.keymap.set("n", "<leader>0", ":BufferLineGoTo 0<CR>", { desc = "Go to buffer 0" })
vim.keymap.set("n", "<leader>q", function()
	require("bufdelete").bufdelete(0, true)
end, { desc = "Close current buffer" })
