vim.keymap.set('n', '<leader>ww', ':Neotree toggle<CR>')
vim.keymap.set('n', '<leader>wf', ':Neotree filesystem focus left<CR>')
vim.keymap.set('n', '<leader>wb', ':Neotree buffers focus left<CR>')
vim.keymap.set('n', '<leader>wg', ':Neotree git_status focus left<CR>')
vim.keymap.set('n', '<leader>q', '')
